# Generated by Django 2.2.6 on 2019-11-07 09:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(default='', max_length=100)),
                ('timer', models.DurationField(blank=True, help_text='[DD] [HH:[MM:]]ss[.uuuuuu] format', null=True, verbose_name='timeslot_duration')),
                ('qu_type', models.CharField(choices=[('MCQ', 'QCM '), ('TF', 'Vrai_Faux'), ('OQ', 'Open_Question')], default='QCM', max_length=3)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_smartquizzconf.question_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Open_Question',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Smartquizzconf.Question')),
                ('answer', models.CharField(default='', editable=False, max_length=1000)),
            ],
            options={
                'verbose_name': 'Question Ouverte',
            },
            bases=('Smartquizzconf.question',),
        ),
        migrations.CreateModel(
            name='QCM',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Smartquizzconf.Question')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), size=None)),
                ('correct_answers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1, null=True), blank=True, size=None)),
            ],
            options={
                'verbose_name': 'QCM',
            },
            bases=('Smartquizzconf.question',),
        ),
        migrations.CreateModel(
            name='True_False',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Smartquizzconf.Question')),
                ('answer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vrai Faux',
            },
            bases=('Smartquizzconf.question',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField()),
                ('questions', models.ManyToManyField(to='Smartquizzconf.Question')),
            ],
            options={
                'verbose_name': 'Quiz',
            },
        ),
    ]
