# Generated by Django 2.2.6 on 2019-11-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smartquizzconf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='timer',
            field=models.DurationField(blank=True, help_text='[DD] [HH:[MM:]]ss[.uuuuuu] format', verbose_name='timeslot_duration'),
        ),
    ]
