# Generated by Django 2.2.6 on 2019-11-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smartquizzconf', '0003_auto_20191105_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='open_question',
            options={'verbose_name': 'Question Ouverte'},
        ),
        migrations.AlterModelOptions(
            name='qcm',
            options={'verbose_name': 'QCM'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz'},
        ),
        migrations.AlterModelOptions(
            name='true_false',
            options={'verbose_name': 'Vrai Faux'},
        ),
        migrations.AlterField(
            model_name='question',
            name='timer',
            field=models.DurationField(blank=True, help_text='[DD] [HH:[MM:]]ss[.uuuuuu] format', null=True, verbose_name='timeslot_duration'),
        ),
    ]
