# Generated by Django 2.2.6 on 2019-11-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smartquizzconf', '0004_auto_20191105_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qu_type',
            field=models.CharField(choices=[('MCQ', 'QCM '), ('TF', 'Vrai_Faux'), ('OQ', 'Open_Question')], default='QCM', max_length=3),
        ),
    ]
